import type { ModelMeta, ModelId } from './types';

export const MODELS: Record<ModelId, ModelMeta> = {
  'gpt-5': {
    id: 'gpt-5',
    name: 'GPT-5',
    vendor: 'OpenAI',
    tier: 'frontier',
    contextWindow: 256000,
    costPer1M: { input: 5.0, output: 15.0 },
    avgLatencyMs: 1840,
    reliability: 0.992,
    capabilities: ['reasoning', 'code', 'math', 'tools', 'vision', 'json'],
    region: 'us-east-1',
    privacy: 'tier-2',
  },
  'claude-opus-4.5': {
    id: 'claude-opus-4.5',
    name: 'Claude Opus 4.5',
    vendor: 'Anthropic',
    tier: 'reasoning',
    contextWindow: 200000,
    costPer1M: { input: 6.0, output: 22.5 },
    avgLatencyMs: 2120,
    reliability: 0.994,
    capabilities: ['reasoning', 'code', 'math', 'tools', 'vision', 'long-context'],
    region: 'us-west-2',
    privacy: 'tier-1',
  },
  'claude-sonnet-4.5': {
    id: 'claude-sonnet-4.5',
    name: 'Claude Sonnet 4.5',
    vendor: 'Anthropic',
    tier: 'frontier',
    contextWindow: 200000,
    costPer1M: { input: 3.0, output: 15.0 },
    avgLatencyMs: 980,
    reliability: 0.989,
    capabilities: ['reasoning', 'code', 'tools', 'vision', 'json'],
    region: 'us-west-2',
    privacy: 'tier-1',
  },
  'gemini-2.5-pro': {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    vendor: 'Google',
    tier: 'frontier',
    contextWindow: 2000000,
    costPer1M: { input: 1.25, output: 5.0 },
    avgLatencyMs: 1420,
    reliability: 0.987,
    capabilities: ['reasoning', 'code', 'math', 'tools', 'vision', 'long-context', 'audio'],
    region: 'us-central-1',
    privacy: 'tier-2',
  },
  'deepseek-r2': {
    id: 'deepseek-r2',
    name: 'DeepSeek R2',
    vendor: 'DeepSeek',
    tier: 'reasoning',
    contextWindow: 128000,
    costPer1M: { input: 0.27, output: 1.10 },
    avgLatencyMs: 2680,
    reliability: 0.971,
    capabilities: ['reasoning', 'math', 'code'],
    region: 'eu-west-1',
    privacy: 'tier-2',
  },
  'grok-4': {
    id: 'grok-4',
    name: 'Grok 4',
    vendor: 'xAI',
    tier: 'frontier',
    contextWindow: 256000,
    costPer1M: { input: 5.0, output: 15.0 },
    avgLatencyMs: 1640,
    reliability: 0.978,
    capabilities: ['reasoning', 'code', 'tools', 'realtime'],
    region: 'us-east-1',
    privacy: 'tier-2',
  },
  'llama-4-405b': {
    id: 'llama-4-405b',
    name: 'Llama 4 405B',
    vendor: 'Meta',
    tier: 'frontier',
    contextWindow: 256000,
    costPer1M: { input: 0.90, output: 0.90 },
    avgLatencyMs: 2240,
    reliability: 0.968,
    capabilities: ['reasoning', 'code', 'math', 'tools'],
    region: 'eu-west-1',
    privacy: 'enterprise-only',
  },
  'mistral-large-2': {
    id: 'mistral-large-2',
    name: 'Mistral Large 2',
    vendor: 'Mistral',
    tier: 'frontier',
    contextWindow: 128000,
    costPer1M: { input: 2.0, output: 6.0 },
    avgLatencyMs: 1180,
    reliability: 0.981,
    capabilities: ['reasoning', 'code', 'tools', 'json'],
    region: 'eu-west-1',
    privacy: 'tier-1',
  },
  'gemma-3-27b': {
    id: 'gemma-3-27b',
    name: 'Gemma 3 27B',
    vendor: 'Google',
    tier: 'fast',
    contextWindow: 128000,
    costPer1M: { input: 0.08, output: 0.08 },
    avgLatencyMs: 240,
    reliability: 0.988,
    capabilities: ['classification', 'intent', 'json'],
    region: 'local',
    privacy: 'enterprise-only',
  },
  'qwen-3-4b': {
    id: 'qwen-3-4b',
    name: 'Qwen 3 4B',
    vendor: 'Alibaba',
    tier: 'fast',
    contextWindow: 64000,
    costPer1M: { input: 0.04, output: 0.04 },
    avgLatencyMs: 180,
    reliability: 0.985,
    capabilities: ['classification', 'intent', 'translation'],
    region: 'local',
    privacy: 'enterprise-only',
  },
  'phi-4-mini': {
    id: 'phi-4-mini',
    name: 'Phi-4 Mini',
    vendor: 'Microsoft',
    tier: 'fast',
    contextWindow: 32000,
    costPer1M: { input: 0.03, output: 0.03 },
    avgLatencyMs: 140,
    reliability: 0.983,
    capabilities: ['classification', 'intent', 'math'],
    region: 'local',
    privacy: 'enterprise-only',
  },
  'llama-3.2-3b': {
    id: 'llama-3.2-3b',
    name: 'Llama 3.2 3B',
    vendor: 'Meta',
    tier: 'fast',
    contextWindow: 64000,
    costPer1M: { input: 0.03, output: 0.03 },
    avgLatencyMs: 160,
    reliability: 0.986,
    capabilities: ['classification', 'intent', 'json'],
    region: 'local',
    privacy: 'enterprise-only',
  },
  'gpt-5-judge': {
    id: 'gpt-5-judge',
    name: 'GPT-5 Judge',
    vendor: 'OpenAI',
    tier: 'judge',
    contextWindow: 128000,
    costPer1M: { input: 5.0, output: 15.0 },
    avgLatencyMs: 740,
    reliability: 0.995,
    capabilities: ['verification', 'fact-check', 'hallucination', 'logic'],
    region: 'us-east-1',
    privacy: 'tier-2',
  },
  'claude-judge': {
    id: 'claude-judge',
    name: 'Claude Judge',
    vendor: 'Anthropic',
    tier: 'judge',
    contextWindow: 200000,
    costPer1M: { input: 3.0, output: 15.0 },
    avgLatencyMs: 680,
    reliability: 0.996,
    capabilities: ['verification', 'fact-check', 'hallucination', 'logic', 'safety'],
    region: 'us-west-2',
    privacy: 'tier-1',
  },
};

export const FRONTIER_MODELS: ModelId[] = [
  'gpt-5',
  'claude-opus-4.5',
  'claude-sonnet-4.5',
  'gemini-2.5-pro',
  'deepseek-r2',
  'grok-4',
  'llama-4-405b',
  'mistral-large-2',
];

export const FAST_MODELS: ModelId[] = ['gemma-3-27b', 'qwen-3-4b', 'phi-4-mini', 'llama-3.2-3b'];

export const JUDGE_MODELS: ModelId[] = ['gpt-5-judge', 'claude-judge', 'gemma-3-27b'];

export function modelById(id: ModelId): ModelMeta {
  return MODELS[id];
}

export function formatCost(c: number): string {
  if (c >= 1) return `$${c.toFixed(2)}`;
  if (c >= 0.01) return `$${c.toFixed(3)}`;
  return `$${c.toFixed(4)}`;
}

export function formatLatency(ms: number): string {
  if (ms >= 1000) return `${(ms / 1000).toFixed(2)}s`;
  return `${Math.round(ms)}ms`;
}
